# Generated by Django 6.0 on 2025-12-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MISReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage1_locality_set', models.BooleanField(default=False, verbose_name='Stage 1: Locality Set')),
                ('stage1_gps_check', models.BooleanField(default=False, verbose_name='Stage 1: GPS Check')),
                ('stage2_locality_set', models.BooleanField(default=False, verbose_name='Stage 2: Locality Set')),
                ('stage2_gps_check', models.BooleanField(default=False, verbose_name='Stage 2: GPS Check')),
                ('stage3_locality_set', models.BooleanField(default=False, verbose_name='Stage 3: Locality Set')),
                ('stage3_gps_check', models.BooleanField(default=False, verbose_name='Stage 3: GPS Check')),
                ('final_mis_status', models.BooleanField(default=False, verbose_name='Final: MIS Status Check')),
            ],
            options={
                'verbose_name': 'MIS Workflow',
                'verbose_name_plural': 'MIS Workflows',
            },
        ),
    ]
