# Generated by Django 6.0 on 2025-12-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misreport',
            name='month_name',
        ),
        migrations.AddField(
            model_name='misreport',
            name='bill_approval_status',
            field=models.BooleanField(default=False, verbose_name='Bill Approval Status'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='billing_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20, verbose_name='Billing Month'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='billing_year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049), (2050, 2050)], default=2025, verbose_name='Billing Year'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage1_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage1_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage2_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage2_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage3_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='misreport',
            name='stage3_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='final_mis_status',
            field=models.BooleanField(default=False, verbose_name='Final MIS Status'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage1_gps_check',
            field=models.BooleanField(default=False, verbose_name='GPS Check'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage1_locality_set',
            field=models.BooleanField(default=False, verbose_name='Locality Set'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage2_gps_check',
            field=models.BooleanField(default=False, verbose_name='GPS Check'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage2_locality_set',
            field=models.BooleanField(default=False, verbose_name='Locality Set'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage3_gps_check',
            field=models.BooleanField(default=False, verbose_name='GPS Check'),
        ),
        migrations.AlterField(
            model_name='misreport',
            name='stage3_locality_set',
            field=models.BooleanField(default=False, verbose_name='Locality Set'),
        ),
    ]
