# Generated by Django 6.0 on 2025-12-14 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_misreport_month_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T3BillingKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_zone', models.CharField(max_length=100)),
                ('billing_km', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='T3Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=255)),
                ('billing_zone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='T3AddressLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('assigned_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.t3locality')),
            ],
        ),
    ]
