# Generated by Django 6.0 on 2025-12-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_t3billingkm_t3locality_t3addresslocality'),
    ]

    operations = [
        migrations.CreateModel(
            name='T3BillingZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t3_locality', models.CharField(db_column='t3_locality', max_length=255, unique=True)),
                ('t3_billing_zone', models.CharField(db_column='t3_billing_zone', max_length=255)),
            ],
            options={
                'db_table': 't3_billing_zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_no', models.CharField(max_length=15, unique=True)),
                ('cab_type', models.CharField(blank=True, max_length=10, null=True)),
                ('vehicle_ownership', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('rc_document', models.FileField(blank=True, null=True, upload_to='vehicle_rc/')),
            ],
            options={
                'verbose_name': 'Vehicle List',
                'verbose_name_plural': 'Vehicle List',
            },
        ),
        migrations.AlterModelOptions(
            name='t3billingkm',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='t3locality',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='T3AddressLocality',
        ),
    ]
